# Generated by Django 3.1.6 on 2021-02-25 11:14

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('actores', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('seasons', models.IntegerField()),
                ('episodes', models.IntegerField()),
                ('images', models.ImageField(upload_to='series/')),
                ('rating', models.CharField(max_length=30)),
                ('evaluation', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
