# Generated by Django 3.1.7 on 2021-02-26 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Staff', '0001_initial'),
        ('Accounts', '0001_initial'),
        ('Series', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_actors',
            field=models.ManyToManyField(blank=True, related_name='actor', to='Staff.Actor'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_directors',
            field=models.ManyToManyField(blank=True, related_name='director', to='Staff.Director'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, related_name='movies', to='Movies.Movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_series',
            field=models.ManyToManyField(blank=True, related_name='series', to='Series.Series'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_writers',
            field=models.ManyToManyField(blank=True, related_name='writer', to='Staff.Writer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
