# Generated by Django 3.1.7 on 2021-02-26 12:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.IntegerField()),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='series/episodes/')),
                ('rating', models.CharField(max_length=30)),
                ('evaluation', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('seasons', models.IntegerField()),
                ('episodes', models.IntegerField()),
                ('images', models.ImageField(upload_to='series/')),
                ('rating', models.CharField(max_length=30)),
                ('evaluation', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeriesCritic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('critic', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critics', to='Series.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_critics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
