# Generated by Django 3.1.7 on 2021-02-26 12:03

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Series', '0001_initial'),
        ('Staff', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='actors',
            field=models.ManyToManyField(related_name='series', to='Staff.Actor'),
        ),
        migrations.AddField(
            model_name='series',
            name='director',
            field=models.ManyToManyField(related_name='series', to='Staff.Director'),
        ),
        migrations.AddField(
            model_name='series',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='series',
            name='writer',
            field=models.ManyToManyField(related_name='series', to='Staff.Writer'),
        ),
        migrations.AddField(
            model_name='episode',
            name='actors',
            field=models.ManyToManyField(related_name='episodes', to='Staff.Actor'),
        ),
        migrations.AddField(
            model_name='episode',
            name='director',
            field=models.ManyToManyField(related_name='episodes', to='Staff.Director'),
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eps', to='Series.series'),
        ),
        migrations.AddField(
            model_name='episode',
            name='writer',
            field=models.ManyToManyField(related_name='episodes', to='Staff.Writer'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('series', 'season', 'number')},
        ),
    ]
